/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Anto
 */
public class ComboBox extends javax.swing.JFrame {

    /**
     * Creates new form ComboBox
     */
    public ComboBox() {
        initComponents();
        mostrar_agregar (false);
        
    }
    
    public void mostrar_agregar (boolean ban){
        LAgregarDeporte.setVisible(ban);
        TFNuevoDeporte.setVisible(ban);
        BConfirmar.setVisible(ban);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CBDeporte = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        BAgregar = new javax.swing.JButton();
        LAgregarDeporte = new javax.swing.JLabel();
        TFNuevoDeporte = new javax.swing.JTextField();
        BConfirmar = new javax.swing.JButton();
        BBorrarTodos = new javax.swing.JButton();
        BBorrar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CBDeporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basket", "Voley", "Natacion", "Futbol" }));
        CBDeporte.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBDeporteItemStateChanged(evt);
            }
        });
        jPanel1.add(CBDeporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 21, 279, -1));

        jLabel1.setText("Deporte: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 24, -1, -1));

        BAgregar.setText("Agregar");
        BAgregar.setToolTipText("");
        BAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(BAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        LAgregarDeporte.setText("Deporte:");
        jPanel1.add(LAgregarDeporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 64, -1, -1));
        jPanel1.add(TFNuevoDeporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 61, 90, -1));

        BConfirmar.setText("Confirmar");
        BConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(BConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 61, -1, -1));

        BBorrarTodos.setText("Borrar Todos");
        BBorrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBorrarTodosActionPerformed(evt);
            }
        });
        jPanel1.add(BBorrarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        BBorrar1.setText("Borrar 1 Elemento");
        BBorrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBorrar1ActionPerformed(evt);
            }
        });
        jPanel1.add(BBorrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAgregarActionPerformed
    mostrar_agregar (true);
    }//GEN-LAST:event_BAgregarActionPerformed

    private void BConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConfirmarActionPerformed
        if (!TFNuevoDeporte.getText().isBlank()){
        CBDeporte.addItem(TFNuevoDeporte.getText());
        TFNuevoDeporte.setText("");
        }
        mostrar_agregar (false);
    }//GEN-LAST:event_BConfirmarActionPerformed

    private void BBorrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBorrarTodosActionPerformed
    if (CBDeporte.getItemCount()>0)
        CBDeporte.removeAllItems();
    }//GEN-LAST:event_BBorrarTodosActionPerformed

    private void CBDeporteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBDeporteItemStateChanged
    if (CBDeporte.getItemCount()==0){
        BBorrarTodos.setEnabled(false);
        BBorrar1.setEnabled(false);
    }
    else{
        BBorrarTodos.setEnabled(true);
        BBorrar1.setEnabled(true);
    }
    }//GEN-LAST:event_CBDeporteItemStateChanged

    private void BBorrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBorrar1ActionPerformed
    if (CBDeporte.getItemCount()!=0){
        CBDeporte.removeItemAt(CBDeporte.getSelectedIndex());
    }
    if (CBDeporte.getItemCount()==0){
        BBorrar1.setEnabled(false);
        BBorrarTodos.setEnabled(false);
    }
    }//GEN-LAST:event_BBorrar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAgregar;
    private javax.swing.JButton BBorrar1;
    private javax.swing.JButton BBorrarTodos;
    private javax.swing.JButton BConfirmar;
    private javax.swing.JComboBox<String> CBDeporte;
    private javax.swing.JLabel LAgregarDeporte;
    private javax.swing.JTextField TFNuevoDeporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
