/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author Anto
 */
public class Ejercicio7 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio7
     */
    public Ejercicio7() {
        initComponents();
        CBTipo.setVisible(false);
        LTipoAlquiler.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LAlquiler = new javax.swing.JLabel();
        LTipoAlquiler = new javax.swing.JLabel();
        CBTipo = new javax.swing.JComboBox<>();
        LZona = new javax.swing.JLabel();
        CBBarrio = new javax.swing.JComboBox<>();
        BBorrar = new javax.swing.JButton();
        BAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LAlquiler.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        LAlquiler.setText("Preferencias de Alquiler");
        jPanel1.add(LAlquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        LTipoAlquiler.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LTipoAlquiler.setText("Tipo Alquiler");
        jPanel1.add(LTipoAlquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        CBTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un Tipo de Alquiler", "Casa", "Departamento de 1 dormitorio", "Departamento de 2 dormitorios", "Local comercial", "Galpón" }));
        jPanel1.add(CBTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 460, -1));

        LZona.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LZona.setText("Barrio Zona");
        jPanel1.add(LZona, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        CBBarrio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un Barrio", "Barrio Intevu", "Barrio Danés", "Barrio AGP", "Barrio Mutual", "Barrio CGT", "Barrio Mutual" }));
        CBBarrio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CBBarrioFocusLost(evt);
            }
        });
        CBBarrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBBarrioActionPerformed(evt);
            }
        });
        jPanel1.add(CBBarrio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 460, -1));

        BBorrar.setText("Borrar");
        BBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(BBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 200, 40));

        BAceptar.setText("Aceptar");
        BAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(BAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 200, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAceptarActionPerformed
        if (CBBarrio.getSelectedIndex()!=0 & CBTipo.getSelectedIndex()!=0)
        {   
        String msj="";
        msj="Barrio Seleccionado: " + CBBarrio.getSelectedItem().toString()+
            "\nTipo de Alquiler: " + CBTipo.getSelectedItem().toString();
        JOptionPane.showMessageDialog(null, msj);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Ingrese un valor valido");
        }
    }//GEN-LAST:event_BAceptarActionPerformed

    private void CBBarrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBBarrioActionPerformed
    String op="";
    op=(String) CBBarrio.getSelectedItem();
    if (op!="Seleccione un Barrio")
    {
        CBTipo.setVisible(true);
        LTipoAlquiler.setVisible(true);
    }
    }//GEN-LAST:event_CBBarrioActionPerformed

    private void CBBarrioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CBBarrioFocusLost
    
    
    /*
    
   
    Barrio AGP
    Barrio Mutual
    Barrio CGT
    Barrio Mutual
    */
    }//GEN-LAST:event_CBBarrioFocusLost

    private void BBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBorrarActionPerformed
    CBTipo.setSelectedIndex(0);
    CBTipo.setVisible(false);
    LTipoAlquiler.setVisible(false);
    CBBarrio.setSelectedIndex(0);
    }//GEN-LAST:event_BBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAceptar;
    private javax.swing.JButton BBorrar;
    private javax.swing.JComboBox<String> CBBarrio;
    private javax.swing.JComboBox<String> CBTipo;
    private javax.swing.JLabel LAlquiler;
    private javax.swing.JLabel LTipoAlquiler;
    private javax.swing.JLabel LZona;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
