/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Anto
 */
public class Ejercicio4 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio4
     */
    public Ejercicio4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGProvincias = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        RBNeuquen = new javax.swing.JRadioButton();
        RBRioNegro = new javax.swing.JRadioButton();
        RBChubut = new javax.swing.JRadioButton();
        RBSantaCruz = new javax.swing.JRadioButton();
        RBTdf = new javax.swing.JRadioButton();
        BBorrar = new javax.swing.JButton();
        BAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BGProvincias.add(RBNeuquen);
        RBNeuquen.setText("Neuquén");
        jPanel1.add(RBNeuquen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        BGProvincias.add(RBRioNegro);
        RBRioNegro.setText("Rio negro");
        jPanel1.add(RBRioNegro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        BGProvincias.add(RBChubut);
        RBChubut.setText("Chubut");
        jPanel1.add(RBChubut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        BGProvincias.add(RBSantaCruz);
        RBSantaCruz.setText("Santa Cruz");
        jPanel1.add(RBSantaCruz, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        BGProvincias.add(RBTdf);
        RBTdf.setText("Tierra del Fuego");
        jPanel1.add(RBTdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        BBorrar.setText("Borrar");
        BBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(BBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        BAceptar.setText("Aceptar");
        BAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(BAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAceptarActionPerformed
    String mensaje = "";
    if (RBChubut.isSelected())
    {
        mensaje="Chubut";
    }
    if (RBNeuquen.isSelected())
    {
        mensaje="Neuquén";
    }
    if (RBRioNegro.isSelected())
    {
        mensaje="Rio Negro";
    }
    if (RBSantaCruz.isSelected())
    {
        mensaje="Santa Cruz";
    }
    if (RBTdf.isSelected())
    {
        mensaje="Tierra del Fuego";
    }
        JOptionPane.showMessageDialog(null, "Usted seleccion la opciion: " + mensaje);
    }//GEN-LAST:event_BAceptarActionPerformed

    private void BBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBorrarActionPerformed
    BGProvincias.clearSelection();
    }//GEN-LAST:event_BBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAceptar;
    private javax.swing.JButton BBorrar;
    private javax.swing.ButtonGroup BGProvincias;
    private javax.swing.JRadioButton RBChubut;
    private javax.swing.JRadioButton RBNeuquen;
    private javax.swing.JRadioButton RBRioNegro;
    private javax.swing.JRadioButton RBSantaCruz;
    private javax.swing.JRadioButton RBTdf;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
