/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Anto
 */
public class Ejercicio123 extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Ejercicio123() {
        initComponents();
        ocultar_niveles();
    }
    public void ocultar_niveles ()
    {
        CBVInicial.setVisible(false);
        CBVMedio.setVisible(false);
        CBVAvanzado.setVisible(false);
        CBBInicial.setVisible(false);
        CBBMedio.setVisible(false);
        CBBAvanzado.setVisible(false);
        CBFInicial.setVisible(false);
        CBFMedio.setVisible(false);
        CBFAvanzado.setVisible(false);
        CBNInicial.setVisible(false);
        CBNMedio.setVisible(false);
        CBNAvanzado.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LDeportePreferido = new javax.swing.JLabel();
        CBVoley = new javax.swing.JCheckBox();
        CBFutbol = new javax.swing.JCheckBox();
        CBBasket = new javax.swing.JCheckBox();
        CBNatacion = new javax.swing.JCheckBox();
        LDeportePreferido1 = new javax.swing.JLabel();
        CBManana = new javax.swing.JCheckBox();
        CBTarde = new javax.swing.JCheckBox();
        CBNoche = new javax.swing.JCheckBox();
        BAceptar = new javax.swing.JButton();
        Borrar = new javax.swing.JButton();
        CBBAvanzado = new javax.swing.JCheckBox();
        CBNInicial = new javax.swing.JCheckBox();
        CBNMedio = new javax.swing.JCheckBox();
        CBNAvanzado = new javax.swing.JCheckBox();
        CBVInicial = new javax.swing.JCheckBox();
        CBVMedio = new javax.swing.JCheckBox();
        CBFInicial = new javax.swing.JCheckBox();
        CBVAvanzado = new javax.swing.JCheckBox();
        CBFMedio = new javax.swing.JCheckBox();
        CBFAvanzado = new javax.swing.JCheckBox();
        CBBInicial = new javax.swing.JCheckBox();
        CBBMedio = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAMensaje = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LDeportePreferido.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LDeportePreferido.setText("Deporte Preferido");
        jPanel1.add(LDeportePreferido, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 47, -1, -1));

        CBVoley.setText("Voley");
        CBVoley.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBVoleyActionPerformed(evt);
            }
        });
        jPanel1.add(CBVoley, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 48, -1, -1));

        CBFutbol.setText("Futbol");
        CBFutbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBFutbolActionPerformed(evt);
            }
        });
        jPanel1.add(CBFutbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 86, -1, -1));

        CBBasket.setText("Basketball");
        CBBasket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBBasketActionPerformed(evt);
            }
        });
        jPanel1.add(CBBasket, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 124, -1, -1));

        CBNatacion.setText("Natación");
        CBNatacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBNatacionActionPerformed(evt);
            }
        });
        jPanel1.add(CBNatacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 162, -1, -1));

        LDeportePreferido1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LDeportePreferido1.setText("Horarios");
        jPanel1.add(LDeportePreferido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 209, -1, -1));

        CBManana.setText("Mañana");
        jPanel1.add(CBManana, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 210, -1, -1));

        CBTarde.setText("Tarde");
        CBTarde.setToolTipText("");
        jPanel1.add(CBTarde, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 248, -1, -1));

        CBNoche.setText("Noche");
        jPanel1.add(CBNoche, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 286, -1, -1));

        BAceptar.setText("Aceptar");
        BAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(BAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 324, -1, -1));

        Borrar.setText("Borrar");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });
        jPanel1.add(Borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 324, -1, -1));

        CBBAvanzado.setText("Avanzado");
        jPanel1.add(CBBAvanzado, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 123, -1, -1));

        CBNInicial.setText("Inicial");
        CBNInicial.setToolTipText("");
        jPanel1.add(CBNInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 161, -1, -1));

        CBNMedio.setText("Medio");
        jPanel1.add(CBNMedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 161, -1, -1));

        CBNAvanzado.setText("Avanzado");
        jPanel1.add(CBNAvanzado, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 161, -1, -1));

        CBVInicial.setText("Inicial");
        CBVInicial.setToolTipText("");
        jPanel1.add(CBVInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 47, -1, -1));

        CBVMedio.setText("Medio");
        jPanel1.add(CBVMedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 47, -1, -1));

        CBFInicial.setText("Inicial");
        CBFInicial.setToolTipText("");
        jPanel1.add(CBFInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 85, -1, -1));

        CBVAvanzado.setText("Avanzado");
        jPanel1.add(CBVAvanzado, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 47, -1, -1));

        CBFMedio.setText("Medio");
        jPanel1.add(CBFMedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 85, -1, -1));

        CBFAvanzado.setText("Avanzado");
        jPanel1.add(CBFAvanzado, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 85, -1, -1));

        CBBInicial.setText("Inicial");
        CBBInicial.setToolTipText("");
        jPanel1.add(CBBInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 123, -1, -1));

        CBBMedio.setText("Medio");
        jPanel1.add(CBBMedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 123, -1, -1));

        TAMensaje.setEditable(false);
        TAMensaje.setColumns(20);
        TAMensaje.setRows(5);
        jScrollPane1.setViewportView(TAMensaje);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 209, 250, 146));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBFutbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBFutbolActionPerformed
    if (CBFutbol.isSelected())
    {
        CBFInicial.setVisible(true);
        CBFMedio.setVisible(true);
        CBFAvanzado.setVisible(true);
    }
    else
    {
        CBFInicial.setVisible(false);
        CBFMedio.setVisible(false);
        CBFAvanzado.setVisible(false);
    }
    }//GEN-LAST:event_CBFutbolActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
    CBVoley.setSelected(false);
    CBBasket.setSelected(false);
    CBFutbol.setSelected(false);
    CBManana.setSelected(false);
    CBNatacion.setSelected(false);
    CBNoche.setSelected(false);
    CBTarde.setSelected(false);
    TAMensaje.setText("");
    CBVInicial.setVisible(false);
    CBVMedio.setVisible(false);
    CBVAvanzado.setVisible(false);
    CBBInicial.setVisible(false);
    CBBMedio.setVisible(false);
    CBBAvanzado.setVisible(false);
    CBFInicial.setVisible(false);
    CBFMedio.setVisible(false);
    CBFAvanzado.setVisible(false);
    CBNInicial.setVisible(false);
    CBNMedio.setVisible(false);
    CBNAvanzado.setVisible(false);
    CBVMedio.setSelected(false);
    CBVAvanzado.setSelected(false);
    CBBInicial.setSelected(false);
    CBBMedio.setSelected(false);
    CBBAvanzado.setSelected(false);
    CBFInicial.setSelected(false);
    CBFMedio.setSelected(false);
    CBFAvanzado.setSelected(false);
    CBNInicial.setSelected(false);
    CBNMedio.setSelected(false);
    CBNAvanzado.setSelected(false);
    }//GEN-LAST:event_BorrarActionPerformed

    private void BAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAceptarActionPerformed
    String mens1="Deportes Favoritos: ";
    String mens2="\nTurnos Seleccionados: ";
    if (CBVoley.isSelected())
    {
        mens1=mens1 + "\nVoley";
    }
    if (CBFutbol.isSelected())
    {
        mens1=mens1 + "\nFutbol";
    }
    if (CBBasket.isSelected())
    {
        mens1=mens1 + "\nBasketball";
    }
    if (CBNatacion.isSelected())
    {
        mens1=mens1 + "\nNatación";
    }
    if (CBManana.isSelected())
    {
        mens2=mens2 + "\nMañana";
    }
    if (CBTarde.isSelected())
    {
        mens2=mens2 + "\nTarde";
    }
    if (CBNoche.isSelected())
    {
        mens2=mens2 + "\nNoche";
    }
    TAMensaje.setText(mens1 + mens2);
    }//GEN-LAST:event_BAceptarActionPerformed

    private void CBVoleyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBVoleyActionPerformed
    if (CBVoley.isSelected())
    {
        CBVInicial.setVisible(true);
        CBVMedio.setVisible(true);
        CBVAvanzado.setVisible(true);
    }
    else
    {
        CBVInicial.setVisible(false);
        CBVMedio.setVisible(false);
        CBVAvanzado.setVisible(false);
    }
    }//GEN-LAST:event_CBVoleyActionPerformed

    private void CBBasketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBBasketActionPerformed
    if (CBBasket.isSelected())
    {
        CBBInicial.setVisible(true);
        CBBMedio.setVisible(true);
        CBBAvanzado.setVisible(true);
    }
    else
    {
        CBBInicial.setVisible(false);
        CBBMedio.setVisible(false);
        CBBAvanzado.setVisible(false);
    }
    }//GEN-LAST:event_CBBasketActionPerformed

    private void CBNatacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBNatacionActionPerformed
    if (CBNatacion.isSelected())
    {
        CBNInicial.setVisible(true);
        CBNMedio.setVisible(true);
        CBNAvanzado.setVisible(true);
    }
    else
    {
        CBNInicial.setVisible(false);
        CBNMedio.setVisible(false);
        CBNAvanzado.setVisible(false);
    }
    }//GEN-LAST:event_CBNatacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio123.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio123.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio123.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio123.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio123().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAceptar;
    private javax.swing.JButton Borrar;
    private javax.swing.JCheckBox CBBAvanzado;
    private javax.swing.JCheckBox CBBInicial;
    private javax.swing.JCheckBox CBBMedio;
    private javax.swing.JCheckBox CBBasket;
    private javax.swing.JCheckBox CBFAvanzado;
    private javax.swing.JCheckBox CBFInicial;
    private javax.swing.JCheckBox CBFMedio;
    private javax.swing.JCheckBox CBFutbol;
    private javax.swing.JCheckBox CBManana;
    private javax.swing.JCheckBox CBNAvanzado;
    private javax.swing.JCheckBox CBNInicial;
    private javax.swing.JCheckBox CBNMedio;
    private javax.swing.JCheckBox CBNatacion;
    private javax.swing.JCheckBox CBNoche;
    private javax.swing.JCheckBox CBTarde;
    private javax.swing.JCheckBox CBVAvanzado;
    private javax.swing.JCheckBox CBVInicial;
    private javax.swing.JCheckBox CBVMedio;
    private javax.swing.JCheckBox CBVoley;
    private javax.swing.JLabel LDeportePreferido;
    private javax.swing.JLabel LDeportePreferido1;
    private javax.swing.JTextArea TAMensaje;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
