/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Anto
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Principal
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LMenuPrincipal = new javax.swing.JLabel();
        BEjercicio123 = new javax.swing.JToggleButton();
        BEjercicio4 = new javax.swing.JToggleButton();
        BSpinner = new javax.swing.JToggleButton();
        BEjercicio5 = new javax.swing.JToggleButton();
        BEjercicio6 = new javax.swing.JToggleButton();
        BEjercicio7 = new javax.swing.JToggleButton();
        BEjercicio8 = new javax.swing.JToggleButton();
        BEjercicio9 = new javax.swing.JToggleButton();
        BEjercicio10 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LMenuPrincipal.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        LMenuPrincipal.setText("Menu Principal");

        BEjercicio123.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        BEjercicio123.setText("Ejercicio 1 - 2 - 3");
        BEjercicio123.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEjercicio123ActionPerformed(evt);
            }
        });

        BEjercicio4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        BEjercicio4.setText("Ejercicio 4");
        BEjercicio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEjercicio4ActionPerformed(evt);
            }
        });

        BSpinner.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        BSpinner.setText("Spinner");
        BSpinner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSpinnerActionPerformed(evt);
            }
        });

        BEjercicio5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        BEjercicio5.setText("Ejercicio 5");
        BEjercicio5.setToolTipText("");
        BEjercicio5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEjercicio5ActionPerformed(evt);
            }
        });

        BEjercicio6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        BEjercicio6.setText("Ejercicio 6");
        BEjercicio6.setToolTipText("");
        BEjercicio6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEjercicio6ActionPerformed(evt);
            }
        });

        BEjercicio7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        BEjercicio7.setText("Ejercicio 7");
        BEjercicio7.setToolTipText("");
        BEjercicio7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEjercicio7ActionPerformed(evt);
            }
        });

        BEjercicio8.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        BEjercicio8.setText("Ejercicio 8");
        BEjercicio8.setToolTipText("");
        BEjercicio8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEjercicio8ActionPerformed(evt);
            }
        });

        BEjercicio9.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        BEjercicio9.setText("ComboBox");
        BEjercicio9.setToolTipText("");
        BEjercicio9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEjercicio9ActionPerformed(evt);
            }
        });

        BEjercicio10.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        BEjercicio10.setText("Lista");
        BEjercicio10.setToolTipText("");
        BEjercicio10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEjercicio10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(LMenuPrincipal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BEjercicio5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BEjercicio123, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BEjercicio8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BEjercicio6, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(BEjercicio4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BEjercicio9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BEjercicio7, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(BSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BEjercicio10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(110, 110, 110))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(LMenuPrincipal)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BEjercicio123)
                    .addComponent(BEjercicio4)
                    .addComponent(BSpinner))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BEjercicio5)
                    .addComponent(BEjercicio6)
                    .addComponent(BEjercicio7))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BEjercicio8)
                    .addComponent(BEjercicio9)
                    .addComponent(BEjercicio10))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BEjercicio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEjercicio4ActionPerformed
    Ejercicio4 ej4= new Ejercicio4 ();
    ej4.setVisible(true);
    ej4.setTitle("Ejercicio 4");
    this.dispose();
    }//GEN-LAST:event_BEjercicio4ActionPerformed

    private void BEjercicio123ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEjercicio123ActionPerformed
    Ejercicio123 ej123= new Ejercicio123();
    ej123.setVisible(true);
    ej123.setTitle("Ejercicio 1 - 2 - 3");
    this.dispose();
    }//GEN-LAST:event_BEjercicio123ActionPerformed

    private void BSpinnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSpinnerActionPerformed
    Spinner spi= new Spinner ();
    spi.setVisible(true);
    spi.setTitle("Spinner");
    this.dispose();
    }//GEN-LAST:event_BSpinnerActionPerformed

    private void BEjercicio5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEjercicio5ActionPerformed
    Ejercicio5 ej5= new Ejercicio5();
    ej5.setVisible(true);
    ej5.setTitle("Ejercicio 5");
    this.dispose();
    }//GEN-LAST:event_BEjercicio5ActionPerformed

    private void BEjercicio6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEjercicio6ActionPerformed
    Ejercicio6 ej6= new Ejercicio6();
    ej6.setVisible(true);
    ej6.setTitle("Ejercicio 6");
    this.dispose();
    }//GEN-LAST:event_BEjercicio6ActionPerformed

    private void BEjercicio7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEjercicio7ActionPerformed
    Ejercicio7 ej7= new Ejercicio7();
    ej7.setVisible (true);
    ej7.setTitle("Ejercicio 7");
    this.dispose();
    }//GEN-LAST:event_BEjercicio7ActionPerformed

    private void BEjercicio8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEjercicio8ActionPerformed
    Ejercicio8 ej8 = new Ejercicio8();
    ej8.setVisible(true);
    ej8.setTitle("Ejercicio 8");
    this.dispose ();
    }//GEN-LAST:event_BEjercicio8ActionPerformed

    private void BEjercicio9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEjercicio9ActionPerformed
    ComboBox combo =new ComboBox();
    combo.setVisible(true);
    this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_BEjercicio9ActionPerformed

    private void BEjercicio10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEjercicio10ActionPerformed
    Lista list=new Lista();
    list.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_BEjercicio10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BEjercicio10;
    private javax.swing.JToggleButton BEjercicio123;
    private javax.swing.JToggleButton BEjercicio4;
    private javax.swing.JToggleButton BEjercicio5;
    private javax.swing.JToggleButton BEjercicio6;
    private javax.swing.JToggleButton BEjercicio7;
    private javax.swing.JToggleButton BEjercicio8;
    private javax.swing.JToggleButton BEjercicio9;
    private javax.swing.JToggleButton BSpinner;
    private javax.swing.JLabel LMenuPrincipal;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
