/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Anto
 */
public class Spinner extends javax.swing.JFrame {

    /**
     * Creates new form Spinner
     */
    public Spinner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LTitulo = new javax.swing.JLabel();
        SLitoral = new javax.swing.JSpinner();
        SPatagonia = new javax.swing.JSpinner();
        SNorte = new javax.swing.JSpinner();
        SCentro = new javax.swing.JSpinner();
        LLitoral = new javax.swing.JLabel();
        LPatagonia = new javax.swing.JLabel();
        LNorte = new javax.swing.JLabel();
        LCentro = new javax.swing.JLabel();
        BVer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TPMensaje = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LTitulo.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        LTitulo.setText("Control Spinner");
        jPanel1.add(LTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        SLitoral.setModel(new javax.swing.SpinnerListModel(new String[] {"Misiones", "Corrientes", "Entre Ríos", "Chaco", "Formosa", "Santa Fe"}));
        jPanel1.add(SLitoral, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 210, -1));

        SPatagonia.setModel(new javax.swing.SpinnerListModel(new String[] {"Chubut", "Rio Negro", "Santa Cruz", "Tierra del Fuego", "Antartida"}));
        jPanel1.add(SPatagonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 210, -1));

        SNorte.setModel(new javax.swing.SpinnerListModel(new String[] {"Catamarca", "Jujuy", "Salta", "Santiago del Estero", "Tucumán"}));
        jPanel1.add(SNorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 210, -1));

        SCentro.setModel(new javax.swing.SpinnerListModel(new String[] {"Córdoba", "Buenos Aires", "La Pampa"}));
        jPanel1.add(SCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 210, -1));

        LLitoral.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        LLitoral.setText("Region Litoral");
        jPanel1.add(LLitoral, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        LPatagonia.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        LPatagonia.setText("Region Patagonia");
        jPanel1.add(LPatagonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        LNorte.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        LNorte.setText("Region Norte");
        jPanel1.add(LNorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        LCentro.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        LCentro.setText("Region Centro");
        jPanel1.add(LCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        BVer.setText("Ver");
        BVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVerActionPerformed(evt);
            }
        });
        jPanel1.add(BVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 30));

        TPMensaje.setEditable(false);
        jScrollPane1.setViewportView(TPMensaje);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 340, 160));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVerActionPerformed
    String mensaje ="";
    mensaje ="Provincia del Litoral: " + SLitoral.getValue() + 
            "\nProvincia de la Patagonia: " + SPatagonia.getValue()+
            "\nProvincia del Norte: " + SNorte.getValue()+ 
            "\nProvincia del Centro: " + SCentro.getValue();
    TPMensaje.setText(mensaje);
    }//GEN-LAST:event_BVerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Spinner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Spinner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Spinner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Spinner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Spinner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BVer;
    private javax.swing.JLabel LCentro;
    private javax.swing.JLabel LLitoral;
    private javax.swing.JLabel LNorte;
    private javax.swing.JLabel LPatagonia;
    private javax.swing.JLabel LTitulo;
    private javax.swing.JSpinner SCentro;
    private javax.swing.JSpinner SLitoral;
    private javax.swing.JSpinner SNorte;
    private javax.swing.JSpinner SPatagonia;
    private javax.swing.JTextPane TPMensaje;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
