/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author Anto
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LNum1 = new javax.swing.JLabel();
        LNum2 = new javax.swing.JLabel();
        LNum3 = new javax.swing.JLabel();
        TFNum3 = new javax.swing.JTextField();
        TFNum1 = new javax.swing.JTextField();
        TFNum2 = new javax.swing.JTextField();
        BPromedio = new javax.swing.JButton();
        BMayor = new javax.swing.JButton();
        BMenor = new javax.swing.JButton();
        LResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LNum1.setText("Numero 1");
        jPanel1.add(LNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        LNum2.setText("Numero 2");
        jPanel1.add(LNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        LNum3.setText("Numero 3");
        jPanel1.add(LNum3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        jPanel1.add(TFNum3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 70, -1));
        jPanel1.add(TFNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 70, -1));
        jPanel1.add(TFNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 70, -1));

        BPromedio.setText("Promedio");
        BPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPromedioActionPerformed(evt);
            }
        });
        jPanel1.add(BPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 100, -1));

        BMayor.setText("Mayor");
        BMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMayorActionPerformed(evt);
            }
        });
        jPanel1.add(BMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 100, -1));

        BMenor.setText("Menor");
        BMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMenorActionPerformed(evt);
            }
        });
        jPanel1.add(BMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 100, -1));
        jPanel1.add(LResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 290, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPromedioActionPerformed
    float num1,num2,num3,res;
    if (TFNum1.getText().isBlank()==true || TFNum2.getText().isBlank()==true || TFNum3.getText().isBlank()==true)
    {
        JOptionPane.showMessageDialog(rootPane, "Falta ingresar un numero");
    }
    else
    {
    num1=Float.parseFloat(TFNum1.getText());
    num2=Float.parseFloat(TFNum2.getText());
    num3=Float.parseFloat(TFNum3.getText());
    res=(num1+num2+num3)/3;
    LResultado.setText("El Promedio es: "+res);
    }
    }//GEN-LAST:event_BPromedioActionPerformed

    private void BMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMayorActionPerformed
    
    if (TFNum1.getText().isBlank()==true || TFNum2.getText().isBlank()==true || TFNum3.getText().isBlank()==true)
    {
        JOptionPane.showMessageDialog(rootPane, "Falta ingresar un numero");
    }
    else
    {
        if (Integer.parseInt(TFNum1.getText())>Integer.parseInt(TFNum2.getText()))
        {
            if (Integer.parseInt(TFNum1.getText())>Integer.parseInt(TFNum3.getText()))
            {
                LResultado.setText( "El Numero Mayor es: "+Integer.parseInt(TFNum1.getText()) );
            }
            else
            {
                LResultado.setText( "El Numero Mayor es: "+Integer.parseInt(TFNum3.getText()) );
            }
        }
        else
        {
            if (Integer.parseInt(TFNum2.getText())>Integer.parseInt(TFNum3.getText()))
            {
                LResultado.setText( "El Numero Mayor es: "+Integer.parseInt(TFNum2.getText()) );
            }
            else
            {
                LResultado.setText( "El Numero Mayor es: "+Integer.parseInt(TFNum3.getText()) );
            }
        }
    }
    
    }//GEN-LAST:event_BMayorActionPerformed

    private void BMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMenorActionPerformed
    
    if (TFNum1.getText().isBlank()==true || TFNum2.getText().isBlank()==true || TFNum3.getText().isBlank()==true)
    {
        JOptionPane.showMessageDialog(rootPane, "Falta ingresar un numero");
    }
    else
    {
        if (Integer.parseInt(TFNum1.getText())<Integer.parseInt(TFNum2.getText()))
        {
            if (Integer.parseInt(TFNum1.getText())<Integer.parseInt(TFNum3.getText()))
            {
                LResultado.setText( "El Numero Mayor es: "+Integer.parseInt(TFNum1.getText()) );
            }
            else
            {
                LResultado.setText( "El Numero Mayor es: "+Integer.parseInt(TFNum3.getText()) );
            }
        }
        else
        {
            if (Integer.parseInt(TFNum2.getText())<Integer.parseInt(TFNum3.getText()))
            {
                LResultado.setText( "El Numero Mayor es: "+Integer.parseInt(TFNum2.getText()) );
            }
            else
            {
                LResultado.setText( "El Numero Mayor es: "+Integer.parseInt(TFNum3.getText()) );
            }
        }
    }
    
    }//GEN-LAST:event_BMenorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BMayor;
    private javax.swing.JButton BMenor;
    private javax.swing.JButton BPromedio;
    private javax.swing.JLabel LNum1;
    private javax.swing.JLabel LNum2;
    private javax.swing.JLabel LNum3;
    private javax.swing.JLabel LResultado;
    private javax.swing.JTextField TFNum1;
    private javax.swing.JTextField TFNum2;
    private javax.swing.JTextField TFNum3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
